### ISSUE TITLE
elm?

### ISSUE THREAD

**Issue by davidmoshal** [survivejs-demos/mobx-demo#4]
Hi just wondering where you were going with the elm project - you left out the code.
Dave

ps: I'm reading your **excellent** book .
Seems like Mobservables might be a better choice than Alt for the example, no?

**Comment by bebraw** [comment]
Hi David,

I don't have any immediate plans for porting to Elm. I did make a note of it based on your suggestion so maybe I'll do the port one day. But now it's too early.

My next major goal is to port the book to Redux. Here's an early [demo](https://github.com/survivejs/redux-demo) if you want to have a look. Alt material will still remain available, but Redux will be the new default for Leanpub readers.

Thanks for the feedback!
